module.exports = {
  ACCEPTABLE_DENOMINATORS : 'USDT,TRY',
  DEFAULT_DENOMINATOR : 'USDT',
  DEFAULT_EXPRESSION : '*/3 * * * *',
  DEFAULT_STOP_LOSS_RATIO : 2,
  DEFAULT_TARGET_GAIN_RATIO : 2,
  DEFAULT_ORDER_AMOUNT : 20,
  STATUS_BEGINNED: 'beginned',
  STATUS_CONNECTED : 'connected',
  STATUS_CONFIGURED : 'configured',
  STATUS_STARTED : 'started',
  STATUS_STOPPED : 'stopped',
  STATUS_RESTARTED : 'restarted'
};